services:
  db:
    image: postgres:16-alpine
    container_name: tcg_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-c", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: tcg_django_web
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --no-input &&
               python manage.py create_superuser &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  bot:
    build: .
    container_name: tcg_telegram_bot
    command: python manage.py startbot
    volumes:
      - .:/app
      - ./media:/app/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: