# Generated by Django 5.2.3 on 2025-06-20 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram User ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Код колоды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('action_cards', models.ManyToManyField(related_name='decks_as_action', to='cards.card', verbose_name='Карты действий')),
                ('character_cards', models.ManyToManyField(related_name='decks_as_character', to='cards.card', verbose_name='Карты персонажей')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='users.telegramuser', verbose_name='Владелец (кто отправил)')),
            ],
            options={
                'verbose_name': 'Колода',
                'verbose_name_plural': 'Колоды',
                'ordering': ['-created_at'],
            },
        ),
    ]
