# Generated by Django 5.2.3 on 2025-06-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='action_cards',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='character_cards',
        ),
        migrations.AddField(
            model_name='deck',
            name='action_card_ids',
            field=models.JSONField(default=list, verbose_name='ID карт действий'),
        ),
        migrations.AddField(
            model_name='deck',
            name='character_card_ids',
            field=models.JSONField(default=list, verbose_name='ID карт персонажей'),
        ),
    ]
