# Generated by Django 5.2.3 on 2025-06-21 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_deck_action_cards_remove_deck_character_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('MESSAGE', 'Получено сообщение'), ('DECK_OK', 'Колода обработана'), ('DECK_FAIL', 'Ошибка обработки колоды'), ('EMPTY_REQ', 'Пустой запрос'), ('COMMAND', 'Использована команда'), ('ERROR', 'Произошла ошибка')], db_index=True, max_length=10, verbose_name='Тип действия')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Действие пользователя',
                'verbose_name_plural': 'Действия пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
