# Generated by Django 5.2.3 on 2025-06-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='card_images/', verbose_name='Изображение'),
        ),
    ]
