# Generated by Django 5.2.3 on 2025-06-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_options_card_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_id'], 'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
