# Generated by Django 5.2.3 on 2025-09-21 12:44
# This is a manually created and edited migration file to correctly apply translations.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_options_remove_card_image'),
    ]

    operations = [
        # Step 1: Rename original fields to become the default English translations.
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='description',
            new_name='description_en',
        ),

        # Step 2: Add the new fields for the Russian language. They must be nullable.
        migrations.AddField(
            model_name='card',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='card',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),

        # Step 3: The original fields that are now the default language must be nullable.
        # The `name` field was not nullable, so we alter it.
        migrations.AlterField(
            model_name='card',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
