# Generated by Django 5.2.3 on 2025-09-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name_en',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Название (EN)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name_ru',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок (RU)'),
        ),
    ]
